blueprint:
  name: Z2M Tuya 2-Button Switch TS0042 by Cabtech inspired by DJF3
  description: "Z2M blueprint for the <strong>Tuya 2-Button wireless remote switch
    TS0042</strong>.<br>  No MQTT topic or Helper needed. version 0.96: simplification
    in blueprint text<br>  Device info: [TS0042](https://www.zigbee2mqtt.io/devices/TS0042.html)
    \n \n       .---.---.    SUPPORTED: \n       |   |   |    - single click \n       | 1 | 2 |
    \   - double click \n       |   |   |    - long click \n       '---'---'\n"
  author: CabaTech
  homeassistant:
    min_version: 2025.3.0
  domain: automation
  input:
    your_remote:
      name: Select your Tuya 2-button remote
      description: ''
      selector:
        device:
          filter:
          - integration: mqtt
            model: Wireless switch with 2 buttons
          multiple: false
    button1_section:
      name: BUTTON 1 (top-left)
      icon: mdi:numeric-1-box-outline
      collapsed: true
      input:
        input_button1_single:
          name: Button 1 - SINGLE click
          description: ''
          default: []
          selector:
            action: {}
        input_button1_double:
          name: Button 1 - DOUBLE click
          description: ''
          default: []
          selector:
            action: {}
        input_button1_long:
          name: Button 1 - LONG click
          description: ''
          default: []
          selector:
            action: {}
    button2_section:
      name: BUTTON 2 (top-right)
      icon: mdi:numeric-2-box-outline
      collapsed: true
      input:
        input_button2_single:
          name: Button 2 - SINGLE click
          description: ''
          default: []
          selector:
            action: {}
        input_button2_double:
          name: Button 2 - DOUBLE click
          description: ''
          default: []
          selector:
            action: {}
        input_button2_long:
          name: Button 2 - LONG click
          description: ''
          default: []
          selector:
            action: {}

  source_url: https://github.com/cabatech/HA-things/blob/main/Z2M-TS0042.yaml
mode: single
trigger:
- domain: mqtt
  device_id: !input your_remote
  type: action
  subtype: 1_single
  id: 1_single
  trigger: device
- domain: mqtt
  device_id: !input your_remote
  type: action
  subtype: 1_double
  id: 1_double
  trigger: device
- domain: mqtt
  device_id: !input your_remote
  type: action
  subtype: 1_hold
  id: 1_hold
  trigger: device
- domain: mqtt
  device_id: !input your_remote
  type: action
  subtype: 2_single
  id: 2_single
  trigger: device
- domain: mqtt
  device_id: !input your_remote
  type: action
  subtype: 2_double
  id: 2_double
  trigger: device
- domain: mqtt
  device_id: !input your_remote
  type: action
  subtype: 2_hold
  id: 2_hold
  trigger: device
conditions: []
actions:
- choose:
  - conditions:
    - condition: trigger
      id:
      - 1_single
    sequence: !input input_button1_single
  - conditions:
    - condition: trigger
      id:
      - 1_double
    sequence: !input input_button1_double
  - conditions:
    - condition: trigger
      id:
      - 1_hold
    sequence: !input input_button1_long
  - conditions:
    - condition: trigger
      id:
      - 2_single
    sequence: !input input_button2_single
  - conditions:
    - condition: trigger
      id:
      - 2_double
    sequence: !input input_button2_double
  - conditions:
    - condition: trigger
      id:
      - 2_hold
    sequence: !input input_button2_long
