blueprint:
  name: Z2M Tuya 1-Button Switch TS0041 by Cabtech inspired by DJF3
  description: "Z2M blueprint for the <strong>Tuya 1-Button wireless remote switch
    TS0041</strong>.<br>  No MQTT topic or Helper needed. version 0.96: simplification
    in blueprint text<br>  Device info: [TS0041](https://www.zigbee2mqtt.io/devices/TS0041.html)
    \n \n       .---.---.    SUPPORTED: \n       |   |   |    - single click \n       | 1 | 2 |
    \   - double click \n       |   |   |    - long click \n       '---'---'\n"
  author: CabaTech
  homeassistant:
    min_version: 2025.3.0
  domain: automation
  input:
    your_remote:
      name: Select your Tuya 1-button remote
      description: ''
      selector:
        device:
          filter:
          - integration: mqtt
            model: Wireless switch with 1 buttons
          multiple: false
    button1_section:
      name: BUTTON 1 (top-left)
      icon: mdi:numeric-1-box-outline
      collapsed: true
      input:
        input_button1_single:
          name: Button 1 - SINGLE click
          description: ''
          default: []
          selector:
            action: {}
        input_button1_double:
          name: Button 1 - DOUBLE click
          description: ''
          default: []
          selector:
            action: {}
        input_button1_long:
          name: Button 1 - LONG click
          description: ''
          default: []
          selector:
            action: {}
  source_url: https://community.home-assistant.io/t/zigbee2mqtt-z2m-tuya-moes-4-button-switch-ts0044-djf3/866315
mode: single
trigger:
- domain: mqtt
  device_id: !input your_remote
  type: action
  subtype: 1_single
  id: 1_single
  trigger: device
- domain: mqtt
  device_id: !input your_remote
  type: action
  subtype: 1_double
  id: 1_double
  trigger: device
- domain: mqtt
  device_id: !input your_remote
  type: action
  subtype: 1_hold
  id: 1_hold
  trigger: device
conditions: []
actions:
- choose:
  - conditions:
    - condition: trigger
      id:
      - 1_single
    sequence: !input input_button1_single
  - conditions:
    - condition: trigger
      id:
      - 1_double
    sequence: !input input_button1_double
  - conditions:
    - condition: trigger
      id:
      - 1_hold
    sequence: !input input_button1_long
